// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-mQjWM3i2FJxU5OC_cqZFzemcSC0NYI',
    appId: '1:337434287287:web:c1a13cf3095f9bc1b54132',
    messagingSenderId: '337434287287',
    projectId: 'tituparty-12b23',
    authDomain: 'tituparty-12b23.firebaseapp.com',
    storageBucket: 'tituparty-12b23.appspot.com',
    measurementId: 'G-YVM6WWEX1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPK0sU_vDL9oo8kzo9_KnSSEc5qbFptUE',
    appId: '1:337434287287:android:d8ef49b7f6ec7fd2b54132',
    messagingSenderId: '337434287287',
    projectId: 'tituparty-12b23',
    storageBucket: 'tituparty-12b23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKnJjP9QjVCwvGih88qEeJxKrd802p_ls',
    appId: '1:337434287287:ios:43982f3300607908b54132',
    messagingSenderId: '337434287287',
    projectId: 'tituparty-12b23',
    storageBucket: 'tituparty-12b23.appspot.com',
    iosBundleId: 'com.example.testSecond',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg-mQjWM3i2FJxU5OC_cqZFzemcSC0NYI',
    appId: '1:337434287287:web:022cba7ac01d4bb7b54132',
    messagingSenderId: '337434287287',
    projectId: 'tituparty-12b23',
    authDomain: 'tituparty-12b23.firebaseapp.com',
    storageBucket: 'tituparty-12b23.appspot.com',
    measurementId: 'G-0SY7DBCG8B',
  );

}