// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGnfTgltFcJgedpLWrIGSgj9mSYB_t2fU',
    appId: '1:1049679713510:web:1faebaff001ea1d6695727',
    messagingSenderId: '1049679713510',
    projectId: 'newerror-1dff6',
    authDomain: 'newerror-1dff6.firebaseapp.com',
    storageBucket: 'newerror-1dff6.appspot.com',
    measurementId: 'G-M58F02SD3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAndTcshUHxrFj_gk2kCm1_BTaNhokXol4',
    appId: '1:1049679713510:android:6c25929fef974b80695727',
    messagingSenderId: '1049679713510',
    projectId: 'newerror-1dff6',
    storageBucket: 'newerror-1dff6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADDYWRnGmK8mY-GwmxKGE3l58JyEdG2XA',
    appId: '1:1049679713510:ios:93a29e3a6a7ec118695727',
    messagingSenderId: '1049679713510',
    projectId: 'newerror-1dff6',
    storageBucket: 'newerror-1dff6.appspot.com',
    iosBundleId: 'com.example.fineTrackingApp',
  );
}
