// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGzSmBjxv7VEqhkMR9byOXHXcCyf7MT-g',
    appId: '1:955995175338:web:398d4eb1597d93c5acd3d3',
    messagingSenderId: '955995175338',
    projectId: 'loginapps-6cd94',
    authDomain: 'loginapps-6cd94.firebaseapp.com',
    storageBucket: 'loginapps-6cd94.appspot.com',
    measurementId: 'G-YMTE9LRWNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0R2RWaXwfZJSM6TnDFztQtcmXpbsaGMU',
    appId: '1:955995175338:android:74cbbd037b98dbdbacd3d3',
    messagingSenderId: '955995175338',
    projectId: 'loginapps-6cd94',
    storageBucket: 'loginapps-6cd94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn8MUuyERmwOAUA6f-R8xyOTcldaywqtY',
    appId: '1:955995175338:ios:9a390d27272d3cd4acd3d3',
    messagingSenderId: '955995175338',
    projectId: 'loginapps-6cd94',
    storageBucket: 'loginapps-6cd94.appspot.com',
    iosBundleId: 'com.example.fineTrackingapp',
  );
}
